name: Build Freenet Executable

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3. Install Python dependencies
      # نیازمندی‌های جدید بر اساس کد کامل شما نصب می‌شوند
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller requests qrcode Pillow psutil dnspython

      # 4. Create default sub.txt file
      # یک فایل اشتراک پیش‌فرض ایجاد می‌کند تا برنامه در اولین اجرا خالی نباشد
      - name: Create default sub.txt file
        run: |
          '"barry-far": "https://raw.githubusercontent.com/barry-far/V2ray-Config/refs/heads/main/All_Configs_Sub.txt"' | Out-File -FilePath sub.txt -Encoding utf8
          '"SoliSpirit": "https://raw.githubusercontent.com/SoliSpirit/v2ray-configs/refs/heads/main/all_configs.txt"' | Out-File -FilePath sub.txt -Encoding utf8 -Append
        shell: pwsh

      # 5. Build executable with PyInstaller
      - name: Build executable with PyInstaller
        run: pyinstaller --onefile --noconsole --name Freenet freenet.pyw

      # 6. Prepare artifact for upload
      # فقط فایل اجرایی و فایل اشتراک پیش‌فرض در فایل نهایی قرار می‌گیرند
      - name: Prepare artifact for upload
        run: |
          mkdir release
          copy dist\Freenet.exe release\
          copy sub.txt release\
        shell: cmd

      # 7. Upload artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Freenet-App-Windows
          path: release/
