name: Build Freenet Executable

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the "main" branch
  push:
    branches: [ "main" ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    steps:
      # 1. Checkout repository
      # Checks-out your repository under $GITHUB_WORKSPACE, so the job can access it
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up Python
      # Installs a specific version of Python for the workflow
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3. Install Python dependencies
      # Installs all the required libraries identified from your script imports
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller requests tqdm qrcode Pillow psutil

      # 4. Create default sub.txt file
      # Creates a sub.txt file with default mirrors using PowerShell to ensure UTF-8 encoding.
      - name: Create default sub.txt file
        run: |
          '"barry-far": "https://raw.githubusercontent.com/barry-far/V2ray-Config/refs/heads/main/All_Configs_Sub.txt"' | Out-File -FilePath sub.txt -Encoding utf8
          '"SoliSpirit": "https://raw.githubusercontent.com/SoliSpirit/v2ray-configs/refs/heads/main/all_configs.txt"' | Out-File -FilePath sub.txt -Encoding utf8 -Append
        shell: pwsh

      # 5. Build executable with PyInstaller
      # Runs the PyInstaller command to create the executable
      - name: Build executable with PyInstaller
        run: pyinstaller --onefile --noconsole --icon=icon.ico --name Freenet freenet.pyw

      # 6. Prepare artifact for upload
      # Creates a 'release' directory and copies the final executable, xray.exe, and sub.txt into it
      - name: Prepare artifact for upload
        run: |
          mkdir release
          copy dist\Freenet.exe release\
          copy xray.exe release\
          copy sub.txt release\
        shell: cmd

      # 7. Upload artifact
      # Uploads the 'release' directory so you can download the final package
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Freenet-App-Windows
          path: release/
